# Generated by Django 6.0.6 on 2026-06-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_project_task_created_at_task_project_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'worker', 'verbose_name_plural': 'workers'},
        ),
    ]
